# Generated by Django 5.1.1 on 2025-01-25 11:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.TextField()),
                ('description', models.TextField()),
                ('Ad_image', models.ImageField(blank=True, null=True, upload_to='Advertisement/')),
                ('weburl', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
