# Generated by Django 5.1.1 on 2024-12-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='module_count',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/course/'),
        ),
    ]
