# Generated by Django 5.1.1 on 2025-02-01 07:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0002_advertisementbanner_remove_transaction_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userupload', models.FileField(upload_to='activityupload/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsappv1.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsappv1.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='lmsappv1.user')),
            ],
        ),
    ]
