# Generated by Django 5.1.1 on 2024-12-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0002_remove_course_module_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
