# Generated by Django 5.1.1 on 2024-12-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0004_alter_course_course_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
    ]
