# Generated by Django 5.1.1 on 2024-12-16 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0005_remove_course_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='duration',
        ),
    ]
