# Generated by Django 5.1.1 on 2024-12-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0007_product_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_photo',
            new_name='product_image',
        ),
    ]
