# Generated by Django 5.1.1 on 2024-12-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0008_rename_product_photo_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_price',
        ),
    ]
