# Generated by Django 5.1.1 on 2024-12-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0010_deleteaccount_otp_course_rating_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
